# plugins
plugins: 
  - jekyll-youtube
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer

# Site settings
encoding: utf-8
email:  "mail@juan-medina.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-71726617-1"
comments: true

# SEO settings
title: Juan Medina Personal Blog
description: Personal blog from Juan Medina
url: "http://juan-medina.com"
twitter_username: JuanMedinaCode
default_img: "/assets/img/pp.jpg"

# Profile settings
name: Juan Medina
profile_img: "/assets/img/pp.jpg"
profile: "<b>About Juan Medina</b><br/>
I'm just a normal geek that code all kind of stuff, from complex corporate applications to games.<br/>
<br/>
Games, music, movies and traveling are my escape pods."
social:
  address-card: "https://juan-medina.com/cv"
  github: "https://github.com/juan-medina"
  twitter: "https://twitter.com/JuanMedinaCode"
  stack-overflow: "http://stackoverflow.com/users/7910403/juan-medina"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", ".gitlab-ci.yml", "docs", "build.sh", "serve.sh", "cv.sh"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed